function time_exec = att(p)
    fprintf('Processo %d Estado Crítico\n\n',p)
    pause(1)
    fprintf('Processo %d Estado Crítico\n\n',p)
    pause(1)
    fprintf('Processo %d Estado Crítico\n\n',p)
    pause(1)